### ISSUE TITLE
Predict image with YOLO model " yolov5n6.onnx ''

### ISSUE THREAD

**Issue by hoangthangbk51** [beiyuouo/hcaptcha-model-factory#10]
Dear sir . Can you have me to classification the image with model "yolov5n6.onnx"
I try the other is return the result "0" or "1"
But with this model i don't know witch way to do . 
if possible please give me example code .
thanks for support .

**Comment by beiyuouo** [comment]
No, yolo is for object detection task. It will return the labels, instead of 0 or 1. You can run yolo model follow [this](https://github.com/QIN2DIM/hcaptcha-challenger/blob/main/src/services/hcaptcha_challenger/solutions/yolo.py)
This repo is only for classification task, which not contains yolo model, sorry.
